Completed pipelines for sonarqube and codecov (#39)
* yml and properties files

* fixing "npm i" issue

* Update sonarqube.yml

* Update sonarqube.yml

* Update sonarqube.yml

* adding steps for the backend reports

* added backend test step

* adding codecov action

diff --git a/.github/workflows/sonarqube.yml b/.github/workflows/sonarqube.yml
--- a/.github/workflows/sonarqube.yml
+++ b/.github/workflows/sonarqube.yml
@@ -1,48 +1,63 @@
-#name: SonarQube Code Analysis
-#on:
-#  push:
-#    branches:
-#      - '**'
-#  pull_request:
+name: SonarQube Code Analysis
+on:
+ push:
+   branches:
+     - '**'
+ pull_request:
     
-#jobs:
-#  sonarqube:
-#    name: SonarQube
-#    runs-on: ubuntu-latest
-#    steps:
-#      - uses: actions/checkout@v4
-#        with:
-#          fetch-depth: 0 # Shallow clones should be disabled for a better relevancy of analysis
+jobs:
+ sonarqube:
+   name: SonarQube
+   runs-on: ubuntu-latest
+   steps:
+     - uses: actions/checkout@v4
+       with:
+         fetch-depth: 0 # Shallow clones should be disabled for a better relevancy of analysis
+ 
+     - name: Set up Node
+       uses: actions/setup-node@v4
 
-#      - name: Set up Node
-#        uses: actions/setup-node@v4
+     - name: Install dependencies
+       run: npm install
+       working-directory: ./frontend
 
-#      - name: Install dependencies
-#        run: npm install
-#
-#      - name: Run tests with coverage
-#        run: npm test -- --coverage
+     - name: Run tests with coverage
+       run: npm test -- --coverage
+       working-directory: ./frontend
 
-#      - name: Debug - List coverage directory
-#        run: ls -la coverage || echo "Coverage directory not found"
+     - name: Install virtual environment
+       run: python -m venv .venv
+       working-directory: ./backend
+
+     - name: Install dependencies
+       run: pip install -r ./requirements.txt
+       working-directory: ./backend
+
+     - name: Run tests with coverage
+       run: pytest --cov --cov-branch --cov-report=xml
+    #    run: pytest --cov
+       working-directory: ./backend
+
+     - name: Debug - List coverage directory
+       run: ls -la coverage || echo "Coverage directory not found"
      
-#      - name: Debug - Check for lcov.info
-#        run: cat coverage/lcov.info || echo "lcov.info not found"
+     - name: Debug - Check for lcov.info
+       run: cat coverage/lcov.info || echo "lcov.info not found"
         
-#      - name: SonarQube Scan
-#        uses: SonarSource/sonarqube-scan-action@v4
-#        env:
-#          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
-#        with:
-#          args: >
-#            -Dsonar.verbose=true
-#            -Dsonar.projectBaseDir=.
-#            -Dsonar.javascript.lcov.reportPaths=./coverage/lcov.info
-#            -Dsonar.sources=src
-#            -Dsonar.tests=tests
+     - name: SonarQube Scan
+       uses: SonarSource/sonarqube-scan-action@v6
+       env:
+         SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
+       with:
+         args: >
+           -Dsonar.verbose=true
+           -Dsonar.projectBaseDir=.
+           -Dsonar.javascript.lcov.reportPaths=./coverage/lcov.info
+           -Dsonar.sources=./frontend/src,./backend/src
+           -Dsonar.tests=./frontend/tests,./backend/tests
 
-#      - name: Upload coverage to Codecov
-#        uses: codecov/codecov-action@v5
-#        with:
-#          token: ${{ secrets.CODECOV_TOKEN }}
-#          fail_ci_if_error: false
+     - name: Upload coverage to Codecov
+       uses: codecov/codecov-action@v5
+       with:
+         token: ${{ secrets.CODECOV_TOKEN }}
+         fail_ci_if_error: false
